org: eventualiguana
console: true
service: serverless-bolt-js
frameworkVersion: '3'
provider:
  name: aws
  region: us-west-1
  runtime: nodejs14.x
  environment:
    SLACK_SIGNING_SECRET: "384f0d124885e9002fc1d2ca38678467"
    SLACK_BOT_TOKEN: "xoxb-4610823292-3999810566195-woUpvB061zNO49Yccm0CSnsU"
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline