org: eventualiguana
console: true
service: serverless-bolt-js
frameworkVersion: '3'
provider:
  name: aws
  region: us-west-1
  runtime: nodejs14.x
  environment:
    SLACK_SIGNING_SECRET: "8720f43068633b1a744121c8eb9a281c"
    SLACK_BOT_TOKEN: "xoxb-1297207607792-3943670681702-gDmIXvrSB0CpVmf8tz1OML3H"
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline